name: Collect YouTube Ad URLs

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Run ad URL extractor
      run: |
        python scripts/youtube_ad_url_extractor.py "$YOUTUBE_URL"
        cat youtube_ad_urls.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add youtube_ad_urls.txt
        git commit -m "Auto-update: New ad URLs $(date +'%Y-%m-%d')"
        git push


    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 1
