name: Collect YouTube Ad URLs

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run ad URL extractor
      run: |
        python scripts/youtube_ad_url_extractor.py > /dev/null 2>&1
        cat youtube_ad_urls.txt

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet youtube_ad_urls.txt; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.changes.outputs.changes == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add youtube_ad_urls.txt
        git commit -m "Auto-update: New ad URLs $(date +'%Y-%m-%d %H:%M')"
        git push

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 1
